/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialog;

import desa_ciapus.Autonik;
import desa_ciapus.Koneksi;
import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author FUTURE-PC
 */
public class Input_ktp extends javax.swing.JDialog {
    
    Koneksi koneksi = new Koneksi();
    JasperReport jasperReport;
    JasperDesign jasperDesign;
    JasperPrint jasperPrint;
    Map<String, Object> param = new HashMap <String, Object>();
    
    Autonik Autonik = new Autonik();
    
    int xMouse,yMouse;
    String provinsi,kab,kec,desa,kodepos,kepdes;
    
    /**
     * Creates new form Input_ktp
     */
    public Input_ktp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        nik.getEditor().getEditorComponent().addKeyListener(new KeyAdapter(){
        
        @Override
        public void keyReleased(KeyEvent evt){
        
            String biodata=nik.getEditor().getItem().toString();
            
            if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            isi(biodata);
            }
            
            if(evt.getKeyCode()>=65 && evt.getKeyCode()<=90 || evt.getKeyCode()>=96 && evt.getKeyCode()<=105 || evt.getKeyCode()==8){}
            
                nik.setModel(Autonik.getList(biodata));
                if(nik.getItemCount()>0){
                
                    nik.showPopup();
                    if(evt.getKeyCode()!=8){
                    
                        ((JTextComponent)nik.getEditor().getEditorComponent()).select(biodata.length(), nik.getEditor().getItem().toString().length());
                        
                    }else{
                    nik.getEditor().setItem(biodata);
                    }
                    
                }else{
                nik.addItem(biodata);
                }
            
        }    
            
        });
        
        autono();
    }
    
    public void isi(String nik){
        String data[]=Autonik.isi(nik);
        if(data[0]!=null){
        nama.setText(data[1]);
        id.setText(data[0]);
        nokk.setText(data[3]);
        alamat.setText(data[4]);
        rt.setText(data[5]);
        rw.setText(data[6]);    
    }else{
        JOptionPane.showMessageDialog(null, "No NIK belum Pernah Terdaftar, Silahkan Input Data Warga");
    }
    }
    
    private void autono(){
        java.util.Date tanggal = new java.util.Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yy");
        try {
            koneksi.koneksi();
            String sql = "SELECT * FROM r_ktp ORDER BY no_reg DESC";
            ResultSet rs = koneksi.cn.executeQuery(sql);
            if (rs.next()) {
                String no_reg = rs.getString("no_reg").substring(6);
                String AN = "" + (Integer.parseInt(no_reg) + 1);
                String Nol = "";

                if(AN.length()==1)
                {Nol = "0000";}
                else if(AN.length()==2)
                {Nol = "000";}
                else if(AN.length()==3)
                {Nol = "00";}
                else if(AN.length()==4)
                {Nol = "0";}
                else if(AN.length()==5)
                {Nol = "";}
                noreg.setText("F121"+ sdf.format(tanggal) + Nol + AN);
            } else {
                noreg.setText("F1211800001");
            }
            rs.close();
            koneksi.conn.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_rktp1 = new desa_ciapus.Bg_rktp();
        exit = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        noreg = new javax.swing.JTextField();
        nik = new javax.swing.JComboBox<>();
        id = new javax.swing.JTextField();
        nokk = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        rt = new javax.swing.JTextField();
        rw = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRASI KTP");
        setUndecorated(true);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit1.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMouseReleased(evt);
            }
        });

        nama.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("NIK");

        jButton1.setText("CETAK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("NAMA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("NO REGISTRASI");

        noreg.setEditable(false);
        noreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noregActionPerformed(evt);
            }
        });

        nik.setEditable(true);

        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout bg_rktp1Layout = new javax.swing.GroupLayout(bg_rktp1);
        bg_rktp1.setLayout(bg_rktp1Layout);
        bg_rktp1Layout.setHorizontalGroup(
            bg_rktp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_rktp1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(bg_rktp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(bg_rktp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_rktp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(noreg)
                        .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bg_rktp1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bg_rktp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(nokk)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rt, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rw, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(bg_rktp1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addContainerGap())
        );
        bg_rktp1Layout.setVerticalGroup(
            bg_rktp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_rktp1Layout.createSequentialGroup()
                .addGroup(bg_rktp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(bg_rktp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(noreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_rktp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_rktp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_rktp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nokk, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rw, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_rktp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_rktp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void noregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noregActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String t1 = " ";
        int confirm = JOptionPane.showConfirmDialog(this,
                "Ingin Cetak Formulir Atas Nama '"+nama.getText()+"' ?",
                "Konfirmasi Cetak",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION){           
                try{
                    java.util.Date tanggal = new java.util.Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    SimpleDateFormat df = new SimpleDateFormat("yyyy");
                    
                    koneksi.koneksi();
                    String dd = "SELECT * FROM profil_desa";
                    ResultSet rs = koneksi.cn.executeQuery(dd);
                    
                    if (rs.next()) {
                        provinsi = rs.getString(4);
                        kab = rs.getString(5);
                        kec = rs.getString(6);
                        desa = rs.getString(7);
                        kodepos = rs.getString(8);
                        kepdes = rs.getString(3);
                    }
                    
                    String sql="INSERT INTO r_ktp set no_reg='"+noreg.getText()+"',id_warga='"+id.getText()+"',date='"+sdf.format(tanggal)+"'";
                    koneksi.cn.executeUpdate(sql);
                    rs.close();
                    koneksi.conn.close();
                    
                    try {
                        File file = new File("src/report/cf_ktp.jrxml");
                        jasperDesign = JRXmlLoader.load(file);
                        //param.clear();
                        param.put("no", noreg.getText());
                        param.put("nama", nama.getText());
                        param.put("nokk", nokk.getText());
                        param.put("nik", nik.getSelectedItem());
                        param.put("alamat", alamat.getText());
                        param.put("rt", rt.getText());
                        param.put("rw", rw.getText());
                        param.put("provinsi", provinsi);
                        param.put("kab", kab);
                        param.put("kec", kec);
                        param.put("desa", desa);
                        param.put("provinsi", provinsi);
                        param.put("kodepos", kodepos);
                        param.put("kepdes", kepdes);
                        param.put("tahun", df.format(tanggal));
                        param.put("x1", t1);
                        param.put("x2", t1);
                        param.put("x3", t1);
                        jasperReport = JasperCompileManager.compileReport(jasperDesign);
                        jasperPrint = JasperFillManager.fillReport(jasperReport, param, koneksi.getConnection());
                        JasperViewer.viewReport(jasperPrint, false);
                        
                    } catch (Exception e){
                        e.printStackTrace();
                    }
                    this.dispose();
                    
                    
                } catch (SQLException | HeadlessException e) {
                    JOptionPane.showMessageDialog(null, "Gagal");
                    System.out.println(e.getMessage());
                }
            }else if (confirm == JOptionPane.NO_OPTION){
                try{
                    java.util.Date tanggal = new java.util.Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    koneksi.koneksi();
                    String sql="INSERT INTO r_ktp set no_reg='"+noreg.getText()+"',id_warga='"+id.getText()+"',date='"+sdf.format(tanggal)+"'";
                    koneksi.cn.executeUpdate(sql);
                    koneksi.conn.close();
                    autono();
                    nik.setSelectedItem("");
                    nama.setText("");
                } catch (SQLException | HeadlessException e) {
                    JOptionPane.showMessageDialog(null, "Gagal");
                    System.out.println(e.getMessage());
                    }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
        ImageIcon tekan = new ImageIcon(getClass().getResource("/images/exit1.png"));
        exit.setIcon(tekan);
    }//GEN-LAST:event_exitMouseExited

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        ImageIcon tekan = new ImageIcon(getClass().getResource("/images/exit2.png"));
        exit.setIcon(tekan);
    }//GEN-LAST:event_exitMousePressed

    private void exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseReleased
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitMouseReleased

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel4MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_ktp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_ktp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_ktp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_ktp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Input_ktp dialog = new Input_ktp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private desa_ciapus.Bg_rktp bg_rktp1;
    private javax.swing.JLabel exit;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nama;
    private javax.swing.JComboBox<String> nik;
    private javax.swing.JTextField nokk;
    private javax.swing.JTextField noreg;
    private javax.swing.JTextField rt;
    private javax.swing.JTextField rw;
    // End of variables declaration//GEN-END:variables
}
