/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import desa_ciapus.Ss_user;
import dialog.Import_data;
import dialog.Input_ktp;
import dialog.Input_sms;
import dialog.Input_warga;
import dialog.Kelola_rtrw;
import dialog.Input_kk;
import dialog.Input_kkp;
import dialog.Input_pindah;
import dialog.Kelola_surat;
import dialog.Lihat_berita;
import dialog.Sms_inbox;
import dialog.Sms_keluar;
import dialog.Surat_keluar;
import dialog.Tambah_berita;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author Future
 */
public class Index extends javax.swing.JFrame {
    
    int xMouse,yMouse;

    /**
     * Creates new form Index
     */
    String tipe;
    
    int timeRun = 0;
    
    public Index() {
        initComponents();
        user();
        date();
        new Thread()
        {
            public void run()
            {
                 while (timeRun == 0)
                 {
                     Calendar cal = new GregorianCalendar();
                     
                     int hour = cal.get(Calendar.HOUR);
                     int min = cal.get(Calendar.MINUTE);
                     int sec = cal.get(Calendar.SECOND);
                     int AM_PM = cal.get(Calendar.AM_PM);
                     
                     String day_night = ""; 
                     if(AM_PM == 1)
                     {
                         day_night = "PM";
                     }else{
                         day_night = "AM";
                     }
                     
                     String time = hour + ":" + min + ":" + sec + " " +day_night;
                     
                     jam.setText(time);
                 }
            }
        }.start();
        
    }
    
    private void user(){
        nama.setText(Ss_user.getUser2());
    }
    
    private void date(){
        Date tanggal = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyyy");
        date.setText(sdf.format(tanggal));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_index1 = new desa_ciapus.Bg_index();
        exit = new javax.swing.JLabel();
        mini = new javax.swing.JLabel();
        b_ktp = new javax.swing.JLabel();
        b_kk = new javax.swing.JLabel();
        b_pm = new javax.swing.JLabel();
        b_pk = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        b_dktp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        b_dkk = new javax.swing.JLabel();
        b_dpm = new javax.swing.JLabel();
        b_dpk = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit1.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMouseReleased(evt);
            }
        });

        mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mini1.png"))); // NOI18N
        mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miniMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                miniMouseReleased(evt);
            }
        });

        b_ktp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ktp_default.png"))); // NOI18N
        b_ktp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_ktp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_ktpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_ktpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b_ktpMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b_ktpMouseReleased(evt);
            }
        });

        b_kk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kk_default.png"))); // NOI18N
        b_kk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_kk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_kkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_kkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b_kkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b_kkMouseReleased(evt);
            }
        });

        b_pm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warga_default.png"))); // NOI18N
        b_pm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_pm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_pmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_pmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b_pmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b_pmMouseReleased(evt);
            }
        });

        b_pk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pindah_default.png"))); // NOI18N
        b_pk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_pk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_pkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_pkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b_pkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b_pkMouseReleased(evt);
            }
        });

        nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(15, 187, 191));
        nama.setText("Nama Pengguna");

        jam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jam.setForeground(new java.awt.Color(15, 187, 191));
        jam.setText("00:00:00 AM");

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setForeground(new java.awt.Color(15, 187, 191));
        date.setText("06 Februari 1996");

        b_dktp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desa_default.png"))); // NOI18N
        b_dktp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_dktp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_dktpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_dktpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b_dktpMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b_dktpMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 187, 191));
        jLabel1.setText("<--- Log Out");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        b_dkk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/internet_default.png"))); // NOI18N
        b_dkk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_dkk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_dkkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_dkkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b_dkkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b_dkkMouseReleased(evt);
            }
        });

        b_dpm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sms_default.png"))); // NOI18N
        b_dpm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_dpm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_dpmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_dpmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b_dpmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b_dpmMouseReleased(evt);
            }
        });

        b_dpk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/surat_default.png"))); // NOI18N
        b_dpk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_dpk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_dpkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_dpkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b_dpkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b_dpkMouseReleased(evt);
            }
        });

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout bg_index1Layout = new javax.swing.GroupLayout(bg_index1);
        bg_index1.setLayout(bg_index1Layout);
        bg_index1Layout.setHorizontalGroup(
            bg_index1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_index1Layout.createSequentialGroup()
                .addGroup(bg_index1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_index1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mini)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exit))
                    .addGroup(bg_index1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(bg_index1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bg_index1Layout.createSequentialGroup()
                                .addComponent(b_dktp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_dkk))
                            .addGroup(bg_index1Layout.createSequentialGroup()
                                .addComponent(b_ktp)
                                .addGap(82, 82, 82)
                                .addComponent(b_kk)))
                        .addGap(90, 90, 90)
                        .addGroup(bg_index1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bg_index1Layout.createSequentialGroup()
                                .addComponent(b_dpm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_dpk))
                            .addGroup(bg_index1Layout.createSequentialGroup()
                                .addComponent(b_pm)
                                .addGap(107, 107, 107)
                                .addComponent(b_pk)))
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_index1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(237, 237, 237)
                .addComponent(date)
                .addGap(110, 110, 110)
                .addComponent(jam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nama)
                .addGap(54, 54, 54))
        );
        bg_index1Layout.setVerticalGroup(
            bg_index1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_index1Layout.createSequentialGroup()
                .addGroup(bg_index1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(mini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103)
                .addGroup(bg_index1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jam)
                    .addComponent(date)
                    .addComponent(nama)
                    .addComponent(jLabel1))
                .addGap(97, 97, 97)
                .addGroup(bg_index1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_ktp)
                    .addComponent(b_kk)
                    .addComponent(b_pm)
                    .addComponent(b_pk))
                .addGap(56, 56, 56)
                .addGroup(bg_index1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_dktp)
                    .addComponent(b_dkk)
                    .addComponent(b_dpm)
                    .addComponent(b_dpk))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_index1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_index1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        ImageIcon tekan = new ImageIcon(getClass().getResource("/images/exit2.png"));
        exit.setIcon(tekan);
    }//GEN-LAST:event_exitMousePressed

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
        ImageIcon ttekan = new ImageIcon(getClass().getResource("/images/exit1.png"));
        exit.setIcon(ttekan);
    }//GEN-LAST:event_exitMouseExited

    private void exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseReleased
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
                "Yakin Untuk Keluar",
                "Konfirmasi Keluar Program",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
 
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        
        
    }//GEN-LAST:event_exitMouseReleased

    private void miniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMousePressed
        // TODO add your handling code here:
        ImageIcon tekan = new ImageIcon(getClass().getResource("/images/mini2.png"));
        mini.setIcon(tekan);
    }//GEN-LAST:event_miniMousePressed

    private void miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseExited
        // TODO add your handling code here:
        ImageIcon ttekan = new ImageIcon(getClass().getResource("/images/mini1.png"));
        mini.setIcon(ttekan);
    }//GEN-LAST:event_miniMouseExited

    private void miniMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseReleased
        // TODO add your handling code here:
        this.setState(Index.ICONIFIED);
    }//GEN-LAST:event_miniMouseReleased

    private void b_ktpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_ktpMouseEntered
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/ktp_hover.png"));
        b_ktp.setIcon(hover);
    }//GEN-LAST:event_b_ktpMouseEntered

    private void b_ktpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_ktpMousePressed
        // TODO add your handling code here:
        ImageIcon tekan = new ImageIcon(getClass().getResource("/images/ktp_tekan.png"));
        b_ktp.setIcon(tekan);
    }//GEN-LAST:event_b_ktpMousePressed

    private void b_ktpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_ktpMouseExited
        // TODO add your handling code here:
        ImageIcon ttekan = new ImageIcon(getClass().getResource("/images/ktp_default.png"));
        b_ktp.setIcon(ttekan);
    }//GEN-LAST:event_b_ktpMouseExited

    private void b_ktpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_ktpMouseReleased
        // TODO add your handling code here:
        ImageIcon udah = new ImageIcon(getClass().getResource("/images/ktp_hover.png"));
        b_ktp.setIcon(udah);
        
        new Input_ktp(this, rootPaneCheckingEnabled).show();
        
    }//GEN-LAST:event_b_ktpMouseReleased

    private void b_kkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_kkMouseEntered
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/kk_hover.png"));
        b_kk.setIcon(hover);
    }//GEN-LAST:event_b_kkMouseEntered

    private void b_kkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_kkMousePressed
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/kk_tekan.png"));
        b_kk.setIcon(hover);
    }//GEN-LAST:event_b_kkMousePressed

    private void b_kkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_kkMouseExited
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/kk_default.png"));
        b_kk.setIcon(hover);
    }//GEN-LAST:event_b_kkMouseExited

    private void b_kkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_kkMouseReleased
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/kk_hover.png"));
        b_kk.setIcon(hover);
        
        Object[] pilihan = {"BARU","PERPANJANG"};
        
        int tipe = JOptionPane.showOptionDialog(this,
                "Pilih Tipe Input KK",
                "Konfirmasi Tipe Input KK",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, pilihan, pilihan[1]);
        
        if(tipe==0){
            new Input_kk(this, rootPaneCheckingEnabled).show();
        }else if(tipe==1){
            new Input_kkp(this, rootPaneCheckingEnabled).show();
        }
    }//GEN-LAST:event_b_kkMouseReleased

    private void b_pmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_pmMouseEntered
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/warga_hover.png"));
        b_pm.setIcon(hover);
    }//GEN-LAST:event_b_pmMouseEntered

    private void b_pmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_pmMousePressed
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/warga_tekan.png"));
        b_pm.setIcon(hover);
    }//GEN-LAST:event_b_pmMousePressed

    private void b_pmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_pmMouseExited
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/warga_default.png"));
        b_pm.setIcon(hover);
    }//GEN-LAST:event_b_pmMouseExited

    private void b_pmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_pmMouseReleased
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/warga_hover.png"));
        b_pm.setIcon(hover);
                
        Object[] pilihan = {"MANUAL","IMPOR FILE"};
        
        int tipe = JOptionPane.showOptionDialog(this,
                "Pilih Tipe Input Warga",
                "Konfirmasi Input Warga",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, pilihan, pilihan[1]);
        
        if(tipe==0){
            new Input_warga(this, rootPaneCheckingEnabled).show();
        }else if(tipe==1){
            new Import_data(this, rootPaneCheckingEnabled).show();
        }
    }//GEN-LAST:event_b_pmMouseReleased

    private void b_pkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_pkMouseEntered
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/pindah_hover.png"));
        b_pk.setIcon(hover);
    }//GEN-LAST:event_b_pkMouseEntered

    private void b_pkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_pkMousePressed
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/pindah_tekan.png"));
        b_pk.setIcon(hover);
    }//GEN-LAST:event_b_pkMousePressed

    private void b_pkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_pkMouseExited
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/pindah_default.png"));
        b_pk.setIcon(hover);
    }//GEN-LAST:event_b_pkMouseExited

    private void b_pkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_pkMouseReleased
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/pindah_hover.png"));
        b_pk.setIcon(hover);
        
        new Input_pindah(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_b_pkMouseReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void b_dktpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dktpMouseEntered
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/desa_hover.png"));
        b_dktp.setIcon(hover);
    }//GEN-LAST:event_b_dktpMouseEntered

    private void b_dktpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dktpMouseExited
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/desa_default.png"));
        b_dktp.setIcon(hover);
    }//GEN-LAST:event_b_dktpMouseExited

    private void b_dktpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dktpMousePressed
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/desa_tekan.png"));
        b_dktp.setIcon(hover);
    }//GEN-LAST:event_b_dktpMousePressed

    private void b_dktpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dktpMouseReleased
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/desa_hover.png"));
        b_dktp.setIcon(hover);
        
        Object[] pilihan = {"DATA WARGA","KELOLA RTRW"};
        
        int tipe = JOptionPane.showOptionDialog(this,
                "Pilih Tipe Data Desa",
                "Konfirmasi Menu Data Desa",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, pilihan, pilihan[1]);
        
        if(tipe==0){
            new Data_warga().show();
        }else if(tipe==1){
            new Kelola_rtrw(this, rootPaneCheckingEnabled).show();
        }
    }//GEN-LAST:event_b_dktpMouseReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void b_dkkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dkkMouseEntered
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/internet_hover.png"));
        b_dkk.setIcon(hover);
    }//GEN-LAST:event_b_dkkMouseEntered

    private void b_dkkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dkkMouseExited
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/internet_default.png"));
        b_dkk.setIcon(hover);
    }//GEN-LAST:event_b_dkkMouseExited

    private void b_dkkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dkkMousePressed
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/internet_tekan.png"));
        b_dkk.setIcon(hover);
    }//GEN-LAST:event_b_dkkMousePressed

    private void b_dkkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dkkMouseReleased
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/internet_hover.png"));
        b_dkk.setIcon(hover);
        
        Object[] pilihan = {"TAMBAH BERITA","LIHAT BERITA"};
        
        int tipe = JOptionPane.showOptionDialog(this,
                "Pilih Tipe Menu Internet",
                "Konfirmasi Menu Internet",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, pilihan, pilihan[1]);
        
        if(tipe==0){
            new Tambah_berita(this, rootPaneCheckingEnabled).show();
        }else if(tipe==1){
            new Lihat_berita(this, rootPaneCheckingEnabled).show();
        }
    }//GEN-LAST:event_b_dkkMouseReleased

    private void b_dpmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dpmMouseEntered
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/sms_hover.png"));
        b_dpm.setIcon(hover);
    }//GEN-LAST:event_b_dpmMouseEntered

    private void b_dpmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dpmMouseExited
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/sms_default.png"));
        b_dpm.setIcon(hover);
    }//GEN-LAST:event_b_dpmMouseExited

    private void b_dpmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dpmMousePressed
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/sms_tekan.png"));
        b_dpm.setIcon(hover);
    }//GEN-LAST:event_b_dpmMousePressed

    private void b_dpmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dpmMouseReleased
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/sms_hover.png"));
        b_dpm.setIcon(hover);
        
        Object[] pilihan = {"SMS MASUK","KIRIM SMS","SMS KELUAR"};
        
        int tipe = JOptionPane.showOptionDialog(this,
                "Pilih Tipe Data Desa",
                "Konfirmasi Menu Data Desa",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, pilihan, pilihan[1]);
        
        if(tipe==0){
            new Sms_inbox(this, rootPaneCheckingEnabled).show();
        }else if(tipe==1){
            new Input_sms(this, rootPaneCheckingEnabled).show();
        }else if(tipe==2){
            new Sms_keluar(this, rootPaneCheckingEnabled).show();
        }
    }//GEN-LAST:event_b_dpmMouseReleased

    private void b_dpkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dpkMouseEntered
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/surat_hover.png"));
        b_dpk.setIcon(hover);
    }//GEN-LAST:event_b_dpkMouseEntered

    private void b_dpkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dpkMouseExited
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/surat_default.png"));
        b_dpk.setIcon(hover);
    }//GEN-LAST:event_b_dpkMouseExited

    private void b_dpkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dpkMousePressed
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/surat_tekan.png"));
        b_dpk.setIcon(hover);
    }//GEN-LAST:event_b_dpkMousePressed

    private void b_dpkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dpkMouseReleased
        // TODO add your handling code here:
        ImageIcon hover = new ImageIcon(getClass().getResource("/images/surat_hover.png"));
        b_dpk.setIcon(hover);
        
        Object[] pilihan = {"KELOLA SURAT","CETAK SURAT"};
        
        int tipe = JOptionPane.showOptionDialog(this,
                "Pilih Tipe Surat",
                "Konfirmasi Menu Surat",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, pilihan, pilihan[1]);
        
        if(tipe==0){
            new Kelola_surat(this, rootPaneCheckingEnabled).show();
        }else if(tipe==1){
            new Surat_keluar(this, rootPaneCheckingEnabled).show();
        }
    }//GEN-LAST:event_b_dpkMouseReleased

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_dkk;
    private javax.swing.JLabel b_dktp;
    private javax.swing.JLabel b_dpk;
    private javax.swing.JLabel b_dpm;
    private javax.swing.JLabel b_kk;
    private javax.swing.JLabel b_ktp;
    private javax.swing.JLabel b_pk;
    private javax.swing.JLabel b_pm;
    private desa_ciapus.Bg_index bg_index1;
    private javax.swing.JLabel date;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jam;
    private javax.swing.JLabel mini;
    private javax.swing.JLabel nama;
    // End of variables declaration//GEN-END:variables
}
